const phq9 = [
  'Little interest or pleasure in doing things',
  'Feeling down, depressed, or hopeless',
  'Trouble falling or staying asleep, or sleeping too much',
  'Feeling tired or having little energy',
  'Poor appetite or overeating',
  'Feeling bad about yourself or that you are a failure or have let yourself or your family down',
  'Trouble concentrating on things, such as reading the newspaper or watching television',
  'Moving or speaking so slowly that other people could have noticed. Or the opposite: being so figety or restless that you have been moving around a lot more than usual',
  'Thoughts that you would be better off dead, or of hurting yourself',
];

const cesdr = [
  'My appetite was poor',
  'I could not shake off the blues',
  'I had trouble keeping my mind on what I was doing',
  'I felt depressed',
  'My sleep was restless',
  'I felt sad',
  'I could not get going',
  'Nothing made me happy',
  'I felt like a bad person',
  'I lost interest in my usual activites',
  'I slept much more than usual',
  'I felt like I was moving too slowly',
  'I felt fidgety',
  'I wished I were dead',
  'I wanted to hurt myself',
  'I was tired all the time',
  'I did not like myself',
  'I lost a lot of weight without trying to',
  'I had a lot of trouble getting to sleep',
  'I could not focus on the important things',
];

const bdi = [
  {
    0: 'I do not feel sad',
    1: 'I feel sad',
    2: "I am sad all the time and I can't snap out of it.",
    3: "I am so sad and unhappy that I can't stand it.",
  },
  {
    0: 'I am not particularly discouraged about the future.',
    1: 'I feel discouraged about the future.',
    2: 'I feel I have nothing to look forward to.',
    3: 'I feel the future is hopeless and that things cannot improve.',
  },
  {
    0: 'I do not feel like a failure.',
    1: 'I feel I have failed more than the average person.',
    2: 'As I look back on my life, all I can see is a lot of failures.',
    3: 'I feel I am a complete failure as a person.',
  },
  {
    0: 'I get as much satisfaction out of things as I used to.',
    1: "I don't enjoy things the way I used to.",
    2: "I don't get real satisfaction out of anything anymore.",
    3: 'I am dissatisfied or bored with everything.',
  },
  {
    0: "I don't feel particularly guilty",
    1: 'I feel guilty a good part of the time.',
    2: 'I feel quite guilty most of the time.',
    3: 'I feel guilty all of the time.',
  },
  {
    0: "I don't feel I am being punished.",
    1: 'I feel I may be punished',
    2: 'I expect to be punished.',
    3: 'I feel I am being punished.',
  },
  {
    0: "I don't feel disappointed in myself.",
    1: 'I am disappointed in myself.',
    2: 'I am disgusted with myself.',
    3: 'I hate myself.',
  },
  {
    0: "I don't feel I am any worse than anybody else.",
    1: 'I am critical of myself for my weaknesses or mistakes.',
    2: 'I blame myself all the time for my faults',
    3: 'I blame myself for everything bad that happens.',
  },
  {
    0: "I don't have any thoughts of killing myself.",
    1: 'I have thoughts of killing myself, but I would not carry them out.',
    2: 'I would like to kill myself.',
    3: 'I would kill myself if I had the chance.',
  },
  {
    0: "I don't cry any more than usual.",
    1: 'I cry more now than I used to.',
    2: 'I cry all the time now.',
    3: "I used to be able to cry, but now I can't cry even though I want to.",
  },
  {
    0: 'I am no more irritated by things than I ever was.',
    1: 'I am slightly more irritated now than usual.',
    2: 'I am quite annoyed or irritated a good deal of the time.',
    3: 'I feel irritated all the time.',
  },
  {
    0: 'I have not lost interest in other people.',
    1: 'I am less interested in other people than I used to be.',
    2: 'I have lost most of my interest in other people.',
    3: 'I have lost all of my interest in other people.',
  },
  {
    0: 'I make decisions about as well as I ever could.',
    1: 'I put off making decisions more than I used to.',
    2: 'I have greater difficulty in making decisions more than I used to.',
    3: "I can't make decisions at all anymore.",
  },
  {
    0: "I don't feel that I look any worse than I used to.",
    1: 'I am worried that I am looking old or unattractive.',
    2: 'I feel there are permanent changes in my appearance that make me look unattractive.',
    3: 'I believe that I look ugly.',
  },
  {
    0: 'I can work about as well as before.',
    1: 'It takes an extra effort to get started at doing something.',
    2: 'I have to push myself very hard to do anything.',
    3: "I can't do any work at all.",
  },
  {
    0: 'I can sleep as well as usual.',
    1: "I don't sleep as well as I used to.",
    2: 'I wake up 1-2 hours earlier than usual and find it hard to get back to sleep.',
    3: 'I wake up several hours earlier than I used to and cannot get back to sleep.',
  },
  {
    0: "I don't get more tired than usual.",
    1: 'I get tired more easily than I used to.',
    2: 'I get tired from doing almost anything.',
    3: 'I am too tired to do anything.',
  },
  {
    0: 'My appetite is no worse than usual.',
    1: 'My appetite is not as good as it used to be.',
    2: 'My appetite is much worse now.',
    3: 'I have no appetite at all anymore.',
  },
  {
    0: "I haven't lost much weight, if any, lately.",
    1: 'I have lost more than five pounds.',
    2: 'I have lost more than ten pounds. ',
    3: 'I have lost more than fifteen pounds.',
  },
  {
    0: 'I am no more worried about my health than usual.',
    1: 'I am worried about physical problems like aches, pains, upset stomach, orconstipation.',
    2: "I am very worried about physical problems and it's hard to think of much else.",
    3: 'I am so worried about my physical problems that I cannot think of anything else.',
  },
  {
    0: 'I have not noticed any recent change in my interest in sex.',
    1: 'I am less interested in sex than I used to be.',
    2: 'I have almost no interest in sex.',
    3: 'I have lost interest in sex completely.',
  },
];

export { phq9, cesdr, bdi };
